### ISSUE TITLE
Per-example loss not calculated in `mnist.py` tutorial script

### ISSUE THREAD

**Issue by greninja** [owkin/grad-cnns#3]
Hi,

If I am not wrong, isn't the whole point of "per-example gradient computation" first computing the loss of model output wrt each input example and then using that loss to compute gradient for each example?

[This line](https://github.com/owkin/grad-cnns/blob/master/code/examples/mnist.py#L45) in `mnist.py` seem to compute an aggregate loss. I do not understand how per-example gradient is computed here. Unless I am missing something here? Thanks!

**Comment by andrmnl** [comment]
Hi @greninja, the point is computing the **gradients** per example, not the loss. Since you can access the individual gradients, however (via `[p.bgrad for p in model.parameters()]`), you can also compute the loss per example with some work. Hope this makes things clearer :)

**Comment by greninja** [comment]
Thanks for your explanation but I still dont get it. How is an aggregate loss used to compute gradients for each example? Ideally, if there are N examples in a batch, one would first compute N loss values for each of those examples and then compute the gradient corresponding to each example using that example's loss value. Am I missing something here?

**Comment by andrmnl** [comment]
@greninja, to be clearer, it only computes the **gradients of the output** w.r.t. weights and biases, not the **gradients of the loss**.  For that reason, the loss does not matter for computing these individual gradients. This quantity I mentioned above, `individual_gradients = [p.bgrad for p in model.parameters()]`, will be the same regardless of the what loss you choose. Analogously, the usual, batch gradients computed by autograd (which can be obtained from `batch_gradients = [p.grad for p in model.parameters()]`, with no b before grad), also do not depend on the loss.

That being said, the gradients of the loss can, of course, be computed from the gradients of the output, using a simple chain rule, dL/dθ = dL/dy dy/dθ.

**Comment by greninja** [comment]
I see your point now.
